default:
    proso_models:
        random_test:
            nth: 10
        predictive_model:
            class: proso.models.prediction.PFAEStaircase
            parameters:
              elo_alpha: 0.4
              pfae_good: 2.6
              pfae_bad: 0.7
        option_selector:
            class: proso.models.option_selection.AdjustedOptionSelection
        options_number:
            class: AdjustedOptionsNumber
            parameters:
                allow_zero_options_restriction: false
        mastery_threshold: 0.901
        practice:
            common:
                set_length: 10
                save_answer_immediately: false
                cache_context: true
                queue_length: 10
        empty_option_set:
            force_direction: t2d
    proso_common:
        logging:
            js_errors: true
    proso_flashcards:
    proso_feedback:
        domain: anatom.cz
        to: [anatom@googlegroups.com]
        evaluation_checkpoints: [30, 70, 120, 200]

