proso_models:
  options_number.parameters.allow_zero_options_restriction:
    - value: true
      condition_key: practice_filter_contains
      condition_value: category/relations
  options_number.parameters.allow_zero_options_restriction:
    - value: true
      condition_key: device
      condition_value: touchscreen
  random_test.nth:
    - value: -1
      condition_key: has_active_subscription
      condition_value: full
    - value: -1
      condition_key: practice_filter_contains
      condition_value: category/relations
  item_selector.class:
    - value: proso.models.item_selection.RandomItemSelection
      condition_key: practice_filter_contains
      condition_value: category/relations
